### ISSUE TITLE
Please support dynamic AuthConfig (needed to pull sandbox from Amazon ECR)

### ISSUE THREAD

**Issue by jmillikin-stripe** [containerd/cri#1131]
The static AuthConfig added in PR https://github.com/containerd/cri/pull/838 doesn't work well for Amazon ECR, which uses a short-lived token for registry authentication. We pull all containers from ECR to reduce the impact of bad network weather, so this missing feature is currently a blocker for migrating from dockershim to containerd-cri.

Docker's credential configuration supports running a separate helper binary, using the wrapper code in [github.com/docker/docker-credential-helpers/client](https://godoc.org/github.com/docker/docker-credential-helpers/client). This works pretty well, and the main cloud vendors have created drop-in credential helpers such as [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper).

Something like this would be perfect:
```toml
[plugins.cri.registry.auths]
  [plugins.cri.registry.auths."https://gcr.io"]
    dockerCredentialHelper = "/usr/local/bin/docker-credential-ecr-login"
```
