### ISSUE TITLE
What is plugins.cri.registry.mirrors means?

### ISSUE THREAD

**Issue by veezhang** [containerd/cri#1138]
If I config like as follows:
```
...
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."gcr.io"]
          endpoint = ["https://gcr.azk8s.cn"]
...
```
And I run the command:
```
ctr pull gcr.io/xxx:yyy
```
Does it means that pull the image replace with https://gcr.azk8s.cn/xxx:yyy?

**Comment by Random-Liu** [comment]
Yeah, it will pull from gcr.azk8s.cn instead.

**Comment by veezhang** [comment]
@Random-Liu I do this, but it doesn't seem to work as well.
```
ctr --debug -n k8s.io images pull gcr.io/google-containers/pause:3.1
DEBU[0000] fetching                                      image="gcr.io/google-containers/pause:3.1"
DEBU[0000] resolving                                    
DEBU[0000] do request                                    request.headers=map[Accept:[application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, *]] request.method=HEAD url="https://gcr.io/v2/google-containers/pause/manifests/3.1"
ctr: failed to resolve reference "gcr.io/google-containers/pause:3.1": failed to do request: Head https://gcr.io/v2/google-containers/pause/manifests/3.1: dial tcp [2404:6800:4008:c01::52]:443: i/o timeout
```
I'm in china, and cannot access gcr.io. And I would to pull  from gcr.azk8s.cn instead without change the images in yaml file.

**Comment by Random-Liu** [comment]
@veezhang Ha, sorry, I forgot.

`plugins.cri.registry` is only for the CRI plugin, containerd itself doesn't have a mirror config. If you want to interact with CRI plugin directly, please use [`crictl`](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md).

**Comment by veezhang** [comment]
@Random-Liu Thanks!
How it work with [micrik8s](https://github.com/ubuntu/microk8s)?

**Comment by Random-Liu** [comment]
@veezhang I think you should use `crictl` if you are using containerd with Kubernetes.

**Comment by veezhang** [comment]
@Random-Liu  Thanks! 
How to configure to pull from https://gcr.azk8s.cn/google-containers/pause:3.1 instead of k8s.gcr.io/pause:3.1???
```
...
        [plugins.cri.registry.mirrors."k8s.gcr.io"]
          endpoint = ["https://gcr.azk8s.cn/google-containers"]
...
```

**Comment by mikebrow** [comment]
[plugins.cri]
... 
  sandbox_image = "gcr.azk8s.cn/google-containers/pause:3.1"

**Comment by veezhang** [comment]
@mikebrow Oh, Thanks!
But I would like to pull all of images from  https://gcr.azk8s.cn  instead of k8s.gcr.io, such k8s.gcr.io/kubernetes-dashboard, k8s.gcr.io/heapster-influxdb, k8s.gcr.io/heapster-grafana and so on .
Is there a way to configure it?

**Comment by mikebrow** [comment]
I thought you already did:
```
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."gcr.io"]
          endpoint = ["https://gcr.azk8s.cn"]
```
and the only problem was the pause image was still hard configured for gcr.io. Have you tried both yet?

**Comment by veezhang** [comment]
@mikebrow Thanks
It really can pull gcr.azk8s.cn/google-containers/pause:3.1, but it cannot pull k8s.gcr.io/pause:3.1 and other images in k8s.gcr.io, k8s.gcr.io/pause:3.1 is just an example.
What I want to configure is that pull mirror.of.example.domain/prefix_uri/image:tag instead of  example.domain/image:tag

```
example.domain/image:tag ==> mirror.of.example.domain/prefix_uri/image:tag
[plugins.cri.registry.mirrors."example.domain"]
  endpoint = ["mirror.of.example.domain/prefix_uri"]
```

**Comment by Random-Liu** [comment]
Does docker registry mirror support that?

**Comment by veezhang** [comment]
@Random-Liu  Sorry, I do not whether it support that.
Thanks a lot!

**Comment by Random-Liu** [comment]
I think we can close this one. :)

**Comment by chrisstafford** [comment]
I've see that this has been closed, but I'm having the same issue as the author. I'm working on an internal network and need to interface with an internal server that has mirrored k8s.gcr.io along with docker.io. But whenever I try to pull an image, it seems to ignore the mirror config. I've followed the documentation here: https://github.com/containerd/containerd/blob/master/docs/registry.md

Am I missing something?

This is my config file
```toml
$ cat /etc/containerd/config.toml
root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0
version = 2

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[debug]
  address = ""
  uid = 0
  gid = 0
  level = ""

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[plugins]
  [plugins.cgroups]
    no_prometheus = false
  [plugins.cri]
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    enable_selinux = false
    sandbox_image = "k8s.gcr.io/pause:3.1"
    stats_collect_period = 10
    systemd_cgroup = true
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    [plugins.cri.containerd]
      snapshotter = "overlayfs"
      no_pivot = false
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = ""
        runtime_root = ""
      [plugins.cri.containerd.untrusted_workload_runtime]
        runtime_type = ""
        runtime_engine = ""
        runtime_root = ""
    [plugins.cri.cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"
      conf_template = ""
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://repos.company.com/docker.io"]
        [plugins.cri.registry.mirrors."k8s.gcr.io"]
          endpoint = ["https://repos.company.com/gcr.io"]
      [plugins.cri.registry.configs]
        [plugins.cri.registry.configs."k8s.gcr.io".tls]
          ca_file = "/etc/ssl/certs/ca-bundle.crt"
          cert_file = "/var/lib/yum/portalbuild-ro.pem"
          key_file = "/var/lib/yum/portalbuild-ro.key"
        [plugins.cri.registry.configs."docker.io".tls]
          ca_file = "/etc/ssl/certs/ca-bundle.crt"
          cert_file = "/var/lib/yum/portalbuild-ro.pem"
          key_file = "/var/lib/yum/portalbuild-ro.key"
    [plugins.cri.x509_key_pair_streaming]
      tls_cert_file = ""
      tls_key_file = ""
  [plugins.diff-service]
    default = ["walking"]
  [plugins.linux]
    shim = "containerd-shim"
    runtime = "runc"
    runtime_root = ""
    no_shim = false
    shim_debug = false
  [plugins.opt]
    path = "/opt/containerd"
  [plugins.restart]
    interval = "10s"
  [plugins.scheduler]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
```

This is what is returned when I check the config
```json
$ sudo crictl --runtime-endpoint /run/containerd/containerd.sock info
{
  "status": {
    "conditions": [
      {
        "type": "RuntimeReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "NetworkReady",
        "status": false,
        "reason": "NetworkPluginNotReady",
        "message": "Network plugin returns error: cni plugin not initialized"
      }
    ]
  },
  "config": {
    "containerd": {
      "snapshotter": "overlayfs",
      "defaultRuntime": {
        "runtimeType": "io.containerd.runtime.v1.linux",
        "runtimeEngine": "",
        "runtimeRoot": "",
        "options": null
      },
      "untrustedWorkloadRuntime": {
        "runtimeType": "",
        "runtimeEngine": "",
        "runtimeRoot": "",
        "options": null
      },
      "runtimes": null,
      "noPivot": false
    },
    "cni": {
      "binDir": "/opt/cni/bin",
      "confDir": "/etc/cni/net.d",
      "confTemplate": ""
    },
    "registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://repos.company.com/docker.io"
          ]
        },
        "k8s.gcr.io": {
          "endpoint": [
            "https://repos.company.com/gcr.io"
          ]
        }
      },
      "auths": null
    },
    "streamServerAddress": "127.0.0.1",
    "streamServerPort": "0",
    "enableSelinux": false,
    "sandboxImage": "k8s.gcr.io/pause:3.1",
    "statsCollectPeriod": 10,
    "systemdCgroup": true,
    "enableTLSStreaming": false,
    "x509KeyPairStreaming": {
      "tlsCertFile": "",
      "tlsKeyFile": ""
    },
    "maxContainerLogSize": 16384,
    "containerdRootDir": "/var/lib/containerd",
    "containerdEndpoint": "/run/containerd/containerd.sock",
    "rootDir": "/var/lib/containerd/io.containerd.grpc.v1.cri",
    "stateDir": "/run/containerd/io.containerd.grpc.v1.cri"
  },
  "golang": "go1.11.5"
}
```

Output when trying to pull an image
```shell
$ sudo crictl --runtime-endpoint /run/containerd/containerd.sock pull k8s.gcr.io/kube-apiserver:v1.19.3
FATA[0030] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "k8s.gcr.io/kube-apiserver:v1.19.3": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.19.3: dial tcp 172.217.197.82:443: i/o timeout
```
Relevant log output
```
Oct 23 00:42:06 stag-lunabuild2-container01 containerd[1493]: time="2020-10-23T00:42:06.831186098Z" level=info msg="PullImage "k8s.gcr.io/kube-apiserver:v1.19.3""
Oct 23 00:42:36 stag-lunabuild2-container01 containerd[1493]: time="2020-10-23T00:42:36.841841081Z" level=error msg="PullImage "k8s.gcr.io/kube-apiserver:v1.19.3" failed" error="failed to resolve image "k8s.gcr.io/kube-apiserver:v1.19.3": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.19.3: dial tcp 172.217.197.82:443: i/o timeout"
```
