### ISSUE TITLE
cri path issue

### ISSUE THREAD

**Issue by kfox1111** [containerd/cri#1279]
Using containerd 1.2.8 or 1.2.9, containers fail to search the path if env PATH is not defined inside the container.

Simple reproducer
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - sh
    - -cxe
    - |
      while true; do
        sleep 1000;
      done
    image: docker.io/gitlab/gitlab-runner-helper:x86_64-latest
    imagePullPolicy: Always
    name: main
```
Much more detail in https://github.com/containerd/containerd/issues/3597

Containers fail like so:
"ad62ed990987fba56502eb63d63b00a4804f2b0c77feb1a2f8b92cd3bb98b1be": OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: "sh": executable file not found in $PATH": unknown
