### ISSUE TITLE
Seccomp at POD level always requires extra syscalls

### ISSUE THREAD

**Issue by pjbgf** [containerd/cri#1393]
**Description**

For a single container pod with `AllowPrivilegeEscalation=false`, setting the seccomp profile at pod or container level results in vastly different syscalls to be whitelisted. 

This is a copy of https://github.com/kubernetes/kubernetes/issues/84623.

**Steps to reproduce the issue:**
1. Spin up a kubernetes cluster with `hack/local-up-cluster.sh`
2. Place the contents of both `*.json` files into `/var/lib/kubelet/seccomp/`
3. Create the pods defined on `pods.yaml` file
4. Confirm that only the pod pod-level-container-perms is **not** running

**Describe the results you received:**
```console
$ kubectl get pods -n default
NAME                        READY   STATUS              RESTARTS   AGE
container-level             1/1     Running             0          7s
pod-level-container-perms   0/1     ContainerCreating   0          7s
pod-level-excessive-perms   1/1     Running             0          7s
```

**Describe the results you expected:**

The same (or similar) pod seccomp profile should work at both container or pod levels. Instead, setting profiles at pod level requires excessive permissions, including: `capset`, `set_tid_address`, `setgid`, `setgroups` and `setuid`.

**Output of `containerd --version`:**

```
containerd github.com/containerd/containerd 1.2.6-0ubuntu1~18.04.2 
```

**Any other relevant information:**
**pods.yaml**:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: container-level
  annotations:
    container.seccomp.security.alpha.kubernetes.io/container-level: 'localhost/container-profile.json'
spec:
  containers:
  - name: container-level
    image: alpine
    command: ["sh"]
    args: ["-c", "echo hi && sleep 120"]
    securityContext:
      allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-level-excessive-perms
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'localhost/pod-profile.json'
spec:
  containers:
  - name: pod-level-excessive-perms
    image: alpine
    command: ["sh"]
    args: ["-c", "echo hi && sleep 120"]
    securityContext:
      allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-level-container-perms
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'localhost/container-profile.json'
spec:
  containers:
  - name: pod-level-container-perms
    image: alpine
    command: ["sh"]
    args: ["-c", "echo hi && sleep 120"]
    securityContext:
      allowPrivilegeEscalation: false
```

**container-profile.json**
```json
{
    "defaultAction": "SCMP_ACT_ERRNO",
    "architectures": [
        "SCMP_ARCH_X86_64",
        "SCMP_ARCH_X86",
        "SCMP_ARCH_X32"
    ],
    "syscalls": [
        {
            "names": [
                "arch_prctl",
                "brk",
                "close",
                "execve",
                "exit_group",
                "futex",
                "mprotect",
                "nanosleep",
                "stat",
                "write"
            ],
            "action": "SCMP_ACT_ALLOW"
        }
    ]
}
```

**pod-profile.json**
```json
{
    "defaultAction": "SCMP_ACT_ERRNO",
    "architectures": [
        "SCMP_ARCH_X86_64",
        "SCMP_ARCH_X86",
        "SCMP_ARCH_X32"
    ],
    "syscalls": [
        {
            "names": [
                "arch_prctl",
                "brk",
                "capget",
                "capset",
                "chdir",
                "close",
                "execve",
                "exit_group",
                "fstat",
                "fstatfs",
                "futex",
                "getdents64",
                "getppid",
                "lstat",
                "mprotect",
                "nanosleep",
                "newfstatat",
                "openat",
                "prctl",
                "read",
                "rt_sigaction",
                "statfs",
                "setgid",
                "setgroups",
                "setuid",
                "stat",
                "uname",
                "write"
            ],
            "action": "SCMP_ACT_ALLOW"
        }
    ]
}
```
