### ISSUE TITLE
[Clarification] Image Pull Issue when using harbor as a Registry Mirror for everything.

### ISSUE THREAD

**Issue by Cellebyte** [containerd/cri#1395]
We have an issue when we want to configure a mirror.
Because we have an airgapped environment we cannot resolve on https://registry-1.docker.io.

Our cri Mirror config looks like this.

```toml
            [plugins.cri.registry.mirrors]
              [plugins.cri.registry.mirrors."docker.io"]
                endpoint = ["http://<ipv4>:<tcp-port"]
              [plugins.cri.registry.mirrors."*"]
                endpoint =  ["http://<ipv4>:<tcp-port"]
```

The Image Pull never happens because cri is Resolving on `docker.io` and `quay.io` but not on the internal mirror registry.

https://github.com/containerd/cri/blob/ae3c28c4d700c02ff5769a8c52c4a325e91c4729/pkg/server/image_pull.go#L97-L99

I thought this is the offending line because I cannot find the implementation of this `registryHosts` function. Could you please help on understanding, why this happens?
