### ISSUE TITLE
Pull images from multiple registries

### ISSUE THREAD

**Issue by JrCs** [containerd/cri#1419]
Hi,
i have create a configuration with multiple registries like this:
```hcl
[plugins.cri.registry.mirrors."test.registry.io"]
  endpoint = ["https://HostIP1:Port1","https://HostIP2:Port2"]
```
But when the first registry (https://HostIP1:Port1) return an html error code (like 404), `crictl pull` not try the second one and directly try to access the direct url (test.registry.io in my example).

**Comment by mikebrow** [comment]
Can I see your config pls.

**Comment by JrCs** [comment]
Sure:

```toml
root = "/var/lib/containerd"
state = "/run/containerd"
# set containerd's OOM score
oom_score = -999

[grpc]
  address = "/run/containerd/containerd.sock"

[debug]
  level = "info"

[plugins]
  [plugins.cgroups]
    no_prometheus = false
  [plugins.cri]
    enable_selinux = false
    sandbox_image = "registry.service.cs.internal:5000/k8s.gcr.io/pause:3.1"
    stats_collect_period = 10
    systemd_cgroup = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    [plugins.cri.cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"
    [plugins.cri.registry.mirrors."docker.io"]
      endpoint = ["https://harbor.mutual.k8s.internal/v2/mirrors/docker.io", "https://registry.service.cs.internal:5000/v2/docker.io"]
    [plugins.cri.registry.mirrors."quay.io"]
      endpoint = ["https://harbor.mutual.k8s.internal/v2/mirrors/quay.io", "https://registry.service.cs.internal:5000/v2/quay.io"]
    [plugins.cri.registry.mirrors."k8s.gcr.io"]
      endpoint = ["https://harbor.mutual.k8s.internal/v2/mirrors/k8s.gcr.io", "https://registry.service.cs.internal:5000/v2/k8s.gcr.io"]
  [plugins.linux]
    # use absolute shim binary path
    shim = "/opt/bin/containerd-shim"
    runtime = "runc"
    no_shim = false
    shim_debug = false
```
