### ISSUE TITLE
cri-containerd cannot pull public image with invalid username/password

### ISSUE THREAD

**Issue by jovizhangwei** [containerd/cri#668]
cri-containerd cannot pull public image with username/password.
We expected containerd should pull the public image whatever username/password given or not.

```
# crictl -r /var/run/cri-containerd.sock pull nginx --creds foo:foo
FATA[0002] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "docker.io/library/nginx:latest": failed to fetch oauth token: unexpected status: 401 Unauthorized
```

```
# crictl -r /var/run/cri-containerd.sock pull nginx
Image is update to date for sha256:73acd1f0cfadf6f56d30351ac633056a4fb50d455fd95b229f564ff0a7adecda
```

Compare with docker, docker can pull public image whatever login succeeded or not. 

I tried to report this issue to containerd, but they suggested cri-containerd could do some improvements similar with what docker does.

Please see: https://github.com/containerd/containerd/issues/2211

**Comment by Random-Liu** [comment]
@jovizhangwei Just curious, in what case, you need `crictl -r /var/run/cri-containerd.sock pull nginx --creds foo:foo` to work?

**Comment by jovizhangwei** [comment]
@Random-Liu take below example:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test1
    image: registry-vpc.cn-hangzhou.aliyuncs.com/jovi/ubuntu #public image
    imagePullPolicy: Always
    command: ["sh", "-c"]
    args: ["set -x; echo $HOSTNAME; sleep 10000"]
  - name: test2
    image: registry-vpc.cn-hangzhou.aliyuncs.com/jovi/nginx:alpine #private image
    imagePullPolicy: Always
    command: ["sh", "-c"]
    args: ["set -x; echo $HOSTNAME; sleep 10000"]
  imagePullSecrets:
  - name: regsecret  #for private image use
  restartPolicy: Never
  automountServiceAccountToken: false
```
Put public image and private image in one pod, with imagePullSecrets for private image. Because public image and private image have some server, so public image will also try to use the imagePullSecrets, then we can found failed to pull public image.

```
Failed to pull image "registry-vpc.cn-hangzhou.aliyuncs.com/jovi/ubuntu": rpc error: code = Unknown desc = failed to resolve image "registry-vpc.cn-hangzhou.aliyuncs.com/jovi/ubuntu:latest": unexpected status code https://registry-vpc.cn-hangzhou.aliyuncs.com/v2/jovi/ubuntu/manifests/latest: 401 Unauthorized
```

If change the container runtime to Docker, then there have no issues.
