### ISSUE TITLE
RunAsGroup is always same as RunAsUser when using it on GKE

### ISSUE THREAD

**Issue by krmayankk** [containerd/cri#836]
I enabled Kubernetes Alpha features in GKE Cluster and installed 1.10.4-gke.2 on it.

Created a Pod with RunAsUser and RunAsGroup, both using different values.

The pod came up fine and the pod Yaml shows the RunAsUser and RunAsGroup set correctly.

When i exec into the pod , i always find the RunAsGroup id same as RunAsUser id even though the RunAsGroup specified in the pod is different.

I tested at both pod level and container level. I believe this seems like a bug in the Containerd implementation. I can provide exact repro if needed .
@Random-Liu

**Comment by krmayankk** [comment]
I had also verified that GKE uses containerd as the Runtime.

**Comment by Random-Liu** [comment]
I can reproduce this. This seems to be a Kubernetes problem.

GKE cluster:
```console
$ kubectl get nodes -o wide
NAME                                  STATUS    ROLES     AGE       VERSION         EXTERNAL-IP      OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
gke-test-default-pool-31e54867-10xf   Ready     <none>    10d       v1.10.4-gke.2   104.154.35.187   Container-Optimized OS from Google   4.14.22+         containerd://1.1.0
gke-test-default-pool-31e54867-7mf6   Ready     <none>    10d       v1.10.4-gke.2   35.232.72.111    Container-Optimized OS from Google   4.14.22+         containerd://1.1.0
gke-test-default-pool-31e54867-vq0w   Ready     <none>    10d       v1.10.4-gke.2   35.192.144.119   Container-Optimized OS from Google   4.14.22+         containerd://1.1.0
```

Pod I use:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: busybox
        command: [ "top" ]
        securityContext:
           runAsUser: 1000
           runAsGroup: 2000
```

Here is the security context containerd gets from kubelet:
```
SecurityContext:&LinuxContainerSecurityContext{  
   Capabilities:nil,
   Privileged:false,
   NamespaceOptions:&NamespaceOption   {  
      Network:POD,
      Pid:CONTAINER,
      Ipc:POD,
   },
   SelinuxOptions:nil,
   RunAsUser:&Int64Value   {  
      Value:1000,
   },
   RunAsUsername:,
   ReadonlyRootfs:false,
   SupplementalGroups:[  
   ],
   ApparmorProfile:,
   SeccompProfilePath:,
   NoNewPrivs:false,
   RunAsGroup:nil,
}
```
